# Generated by Django 3.2.6 on 2022-05-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='Membership discount'),
        ),
        migrations.AddField(
            model_name='membership',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Membership duration'),
        ),
    ]
