# Generated by Django 3.2.6 on 2022-05-20 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0018_alter_booking_booking_reference_number'),
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_number', models.CharField(default=payment.models.Payment.transaction, max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Transaction Number')),
                ('transaction_date', models.DateField(auto_now=True, verbose_name='Transaction date')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Name')),
                ('email', models.CharField(max_length=150, null=True, verbose_name='Email')),
                ('phone', models.BigIntegerField(null=True, verbose_name='Phone Number')),
                ('payment_method', models.CharField(choices=[('PREMIUM', 'Premium'), ('M-PESA', 'M-Pesa'), ('VISA CARD', 'Visa Card'), ('MASTERCARD', 'MasterCard'), ('CASH', 'Cash')], max_length=50, verbose_name='Payment method')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Total to pay')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Premium balance')),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='Premium coupon discount')),
                ('premium_expiration', models.DateField(blank=True, verbose_name='Premium expiry date')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking', verbose_name='booking reference number')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('premium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premium.premium', verbose_name='Premium Number')),
            ],
        ),
    ]
