# Generated by Django 3.2.6 on 2022-05-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booking',
            new_name='booking_reference_number',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='premium',
            new_name='premium_reference_number',
        ),
    ]
