# Generated by Django 3.2.6 on 2022-03-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('type_of_service', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Available extra Service')),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='HairCut',
            fields=[
                ('hair_cut_type', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Type of Haircut')),
                ('picture', models.ImageField(upload_to='Haircut', verbose_name='Image of haircut')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='price')),
            ],
        ),
    ]
