# Generated by Django 3.2.6 on 2022-03-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservice',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='haircut',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='price'),
        ),
    ]
