# Generated by Django 3.2.6 on 2022-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220309_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraservice',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='haircut',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price'),
        ),
    ]
