# Generated by Django 3.2.6 on 2022-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_user',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_user_email',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_username',
        ),
        migrations.AddField(
            model_name='booking',
            name='phonenumber',
            field=models.BigIntegerField(blank=True, default=1254754),
            preserve_default=False,
        ),
    ]
