# Generated by Django 3.2.6 on 2022-03-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
    ]
