# Generated by Django 3.2.6 on 2022-03-28 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0008_remove_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer name'),
        ),
    ]
