# Generated by Django 3.2.6 on 2022-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_extraservice_service_picture'),
        ('booking', '0010_auto_20220328_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='extra_services',
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_services',
            field=models.ManyToManyField(max_length=150, to='services.ExtraService', verbose_name='Extra Service'),
        ),
    ]
