# Generated by Django 3.2.6 on 2022-04-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_extraservice_service_picture'),
        ('booking', '0011_auto_20220420_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='extra_services',
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_services',
            field=models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.extraservice', verbose_name='Extra Service'),
        ),
    ]
