# Generated by Django 3.2.6 on 2022-05-20 07:56

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='pay_now',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=150, null=True, verbose_name='Pay Now'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PREMIUM', 'Premium'), ('M-PESA', 'M-Pesa'), ('VISA CARD', 'Visa Card'), ('MASTERCARD', 'MasterCard'), ('NULL', 'Null')], max_length=150, null=True, verbose_name='Method of Payment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference_number',
            field=models.CharField(default=booking.models.Booking.reference, max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Booking number'),
        ),
    ]
