# Generated by Django 3.2.6 on 2022-05-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_booking_pay_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PREMIUM', 'Premium'), ('M-PESA', 'M-Pesa'), ('VISA CARD', 'Visa Card'), ('MASTERCARD', 'MasterCard'), ('CASH', 'Cash')], max_length=150, null=True, verbose_name='Method of Payment'),
        ),
    ]
