# Generated by Django 3.2.6 on 2022-05-20 09:39

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20220520_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference_number',
            field=models.CharField(default=booking.models.Booking.reference, max_length=30, primary_key=True, serialize=False, verbose_name='Booking number'),
        ),
    ]
