# Generated by Django 3.2.6 on 2022-05-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_booking_booking_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Place'),
        ),
    ]
