# Generated by Django 3.2.6 on 2022-05-20 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import premium.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0002_auto_20220519_1244'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('premium_reference_number', models.CharField(default=premium.models.Premium.premium_number, max_length=30, primary_key=True, serialize=False, verbose_name='Premium number')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Owner name')),
                ('email', models.CharField(max_length=150, null=True, verbose_name='Owner email')),
                ('phone', models.BigIntegerField(null=True, verbose_name='Owner Phone Number')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Premium Starting Date')),
                ('expiry_date', models.DateField(blank=True, verbose_name='Premium expiry date')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='balance')),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='Premium coupon discount')),
                ('isExpired', models.BooleanField(default=False, verbose_name='premium expired status')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.membership', verbose_name='Membership')),
            ],
        ),
    ]
